# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wolfcrypt-py @ EXPOTEC 2016

baseurl: "/expotec-wolfcrypt-py-press"
url: "https://moisesguimaraes.github.io"

email: moises@wolfssl.com

description: > # Esta apresentação contém conceitos básicos de criptografia clássica e moderna,
  e uma introdução à biblioteca wolfCrypt, engine de criptografia por trás da biblioteca wolfSSL
  responsável pela segurança de mais de 1 bilhão de aplicações e dispositivos. Utilizando exemplos
  na linguagem python com a API wolfcrypt-py, tentamos desmistificar um pouco da criptografia para
  público geral, assim como divulgar a ferramenta para desenvolvedores, aumentando o seu "arsenal
  digital".

# Build settings
markdown: kramdown

